database:
  host: "localhost"
  port: "3306"
  user: "root"
  password: "root"
  max_idle: 10
  max_open: 10
  max_life: 24

server:
  port: "8080"

redis:
  host: "localhost"
  port: "6379"
  password: "test"
  db: 2